Java-2. ДЗ 01, Ёров Собир
YorovSobir/java-2-au-course pull request #1
Opened 2017-09-23 12:14 UTC by YorovSobir

@dsavvinov

2017-09-27 11:13 UTC, dsavvinov commented
//cc @sproshev

2017-10-18 21:54 UTC, sproshev requested changes

2017-10-18 21:54 UTC, sproshev commented on ha1/src/main/java/ru/spbau/mit/java2/LightExecutionException.java
> +    public LightExecutionException(String message) {
unused

2017-10-18 21:54 UTC, sproshev commented on ha1/src/main/java/ru/spbau/mit/java2/LightFuture.java
> +    private ThreadPool threadPool;
final

2017-10-18 21:54 UTC, sproshev commented on ha1/src/main/java/ru/spbau/mit/java2/LightFuture.java
> +public class LightFuture<X> implements Runnable {
по заданию LF это интерфейс, который ни от кого не наследуется

2017-10-18 21:54 UTC, sproshev commented on ha1/src/main/java/ru/spbau/mit/java2/LightFuture.java
> +            this.notifyAll();
this не нужен

2017-10-18 21:54 UTC, sproshev commented on ha1/src/main/java/ru/spbau/mit/java2/LightFuture.java
> +                    this.wait();
this

2017-10-18 21:54 UTC, sproshev commented on ha1/src/main/java/ru/spbau/mit/java2/LightFuture.java
> +        return threadPool.submit(supplier);
не пойдет

пусть есть два потока
есть долгая родительская таска, для который мы делаем thenApply
оба потока заняты, вторая таска ждет первую
приходит третья таска, она может и должна быть выполнена, но выполнена не будет, пока не закончится первая таска

2017-10-18 21:54 UTC, sproshev commented on ha1/src/main/java/ru/spbau/mit/java2/ThreadPoolImpl.java
> +        }
зачем два цикла? почему за один не сделать?

2017-10-18 21:54 UTC, sproshev commented on ha1/src/main/java/ru/spbau/mit/java2/api/ThreadPool.java
> +    int activeThread();
лишнее, проверять кол-во потоков нужно иначе

2017-10-18 21:54 UTC, sproshev commented on ha1/src/test/java/ru/spbau/mit/java2/ThreadPoolTest.java
> +    @Test
см аннотацию AfterClass

2017-10-21 09:07 UTC, YorovSobir commented on ha1/src/main/java/ru/spbau/mit/java2/LightExecutionException.java
> +    public LightExecutionException(String message) {
Удалил.

2017-10-21 09:07 UTC, YorovSobir commented on ha1/src/main/java/ru/spbau/mit/java2/LightFuture.java
> +public class LightFuture<X> implements Runnable {
Исправил.

2017-10-21 09:07 UTC, YorovSobir commented on ha1/src/main/java/ru/spbau/mit/java2/LightFuture.java
> +    private ThreadPool threadPool;
Исправил.

2017-10-21 09:08 UTC, YorovSobir commented on ha1/src/main/java/ru/spbau/mit/java2/LightFuture.java
> +                    this.wait();
Исправил.

2017-10-21 09:08 UTC, YorovSobir commented on ha1/src/main/java/ru/spbau/mit/java2/LightFuture.java
> +            this.notifyAll();
Исправил.

2017-10-21 09:11 UTC, YorovSobir commented on ha1/src/main/java/ru/spbau/mit/java2/ThreadPoolImpl.java
> +        }
Да, можно в одном цикле.
Я перепутал с ситуацией когда start и join, поэтому сделал два. Исправил.

2017-10-21 09:11 UTC, YorovSobir commented on ha1/src/main/java/ru/spbau/mit/java2/api/ThreadPool.java
> +    int activeThread();
Исправил.

2017-10-21 12:24 UTC, YorovSobir commented on ha1/src/test/java/ru/spbau/mit/java2/ThreadPoolTest.java
> +    @Test
Если использовать AfterClass, то метод не будет тестовым, а этим методом я проверяю, что shutdown работает правильно. 
Исправил следующим образом: Перед каждым тестом проверяю, если был вызван shutdown, то создаю новый трэдпул, иначе возвращаю старый.

2017-10-21 12:51 UTC, YorovSobir commented on ha1/src/main/java/ru/spbau/mit/java2/LightFuture.java
> +        return threadPool.submit(supplier);
Исправил. Добавил тест.

2017-10-21 12:51 UTC, YorovSobir commented
@sproshev 
Исправил все замечания.

2017-10-26 20:35 UTC, sproshev approved these changes

2017-10-26 20:35 UTC, sproshev commented on ha1/src/main/java/ru/spbau/mit/java2/LightFuture.java
> +    <Y> LightFuture<Y> thenApply(Function<X, Y> function);
`<? super X, Y>`

2017-10-26 20:35 UTC, sproshev commented on ha1/src/main/java/ru/spbau/mit/java2/ThreadPoolImpl.java
> +            throw new RuntimeException("there are not running workers");
лучше IllegalStateException

2017-10-26 20:36 UTC, sproshev commented on ha1/src/main/java/ru/spbau/mit/java2/LightFuture.java
> +            this.notifyAll();
-0.5

2017-10-26 20:36 UTC, sproshev commented on ha1/src/main/java/ru/spbau/mit/java2/LightFuture.java
> +        return threadPool.submit(supplier);
-0.5

2017-10-26 20:36 UTC, sproshev commented on ha1/src/main/java/ru/spbau/mit/java2/LightFuture.java
> +    <Y> LightFuture<Y> thenApply(Function<X, Y> function);
-0.25

2017-11-09 07:19 UTC, merged